### ISSUE TITLE
Move to a database

### ISSUE THREAD

**Issue by alfawal** [pepsizerosugar/python-ping-tester#7]
Because of #5 the user will not need to edit the servers list directly.
So, consider moving the data into a database like sqlite3.
Working with a database has so many advantages.

**Comment by pepsizerosugar** [comment]
@alfawal 
It is not simply a ping test app for 'Escape from Tarkov' game, so moving the server list to the DB needs more confirmation.

Because now in JSON format, if you write or paste only according to the format, it will be applied immediately, but if you move to DB, the user has to rely only on UI Dialog or use a 3rd-party DB tool.

Btw in the 1.5.0 branch, I wrote a CRUD method using sqlite3, and I am thinking of UX Flow as to how to show the dialog to the end user.

Is there any UX or UI that I can refer to?

**Comment by alfawal** [comment]
I do kinda agree to stay on JSON file for simplicity.
Lets apply #8 to the JSON file then!
